### ISSUE TITLE
Style Header

### ISSUE THREAD

**Issue by NicWille** [NicWille/group1#4]
1.  Search bar  should be composed of 3 elements in a row; label, input, button.
2.  Search bar should be large, and centered near or at the top of the page

**Comment by Chetana16032002** [comment]
html :
<body>
    <link rel="stylesheet" href="styles.css">
    <div class="box">
         <input type="search" id="search" placeholder="Search" />
    </div>
    
</body>
css :
.box{
    /* width: 100%;
    text-align: center; */
    margin-right:auto;
    margin-left:auto;
    width:100px; /* Set this property to whatever you like */
}

#search {
    margin: 0 auto;
    display: block;

}

// name the css file as styles.css
